# Generated by Django 4.2.9 on 2024-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
