# Generated by Django 4.2.9 on 2024-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_alter_feature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
