# Generated by Django 4.2.9 on 2024-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0004_herosection_rename_benefit_benefitsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('items', models.ManyToManyField(to='invoicer.item')),
            ],
        ),
    ]
